# Generated by Django 4.2.5 on 2023-11-10 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='Alumnos',
        ),
    ]
