# Generated by Django 4.2.5 on 2023-11-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0002_rename_alumno_alumnos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='Appellido',
            new_name='Apellido',
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
