# Generated by Django 4.2.5 on 2023-11-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0003_rename_appellido_alumnos_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='imagen',
            field=models.ImageField(blank=True, default='static/img/default.jpg', null=True, upload_to='img'),
        ),
    ]
